name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - source

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test: # make sure the action works on a clean machine without building
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Mysql
        run: |
          git clone https://github.com/docker-library/mysql.git
      - uses: alicesu55/condom@build
        with:
          folder: '8.0'
      - name: Mysql Should Compile
        run: |
          cat mysql/8.0/Dockerfile 
          cd mysql/8.0; docker build -t mysql8 .

  deploy: # make sure build/ci work properly
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: stage
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}